### PR TITLE
detect with toString

### PR DESCRIPTION
**Pull request by JoelEinbinder**
Found you!

### CODE REVIEW

**Comment by JoelEinbinder** [comment]
It detects protocol

**Comment by paulirish** [comment]
oh boy.

**Comment by antoinevastel** [comment]
There is the same problem with navigator.webdriver that is also present in non headless mode. It depends if the goal is to detect only Chrome headless, or more globally automated Chrome.

**Comment by paulirish** [comment]
Good call. I added some comments on this one and webdriver to describe that they are adjacent detects: a6a2c89503727ad4bd26b7932ad52bfcabd21e7f

Also fwiw, the `navigator.webdriver` object is created if either `--headless` or `--enable-automation` is provided: https://cs.chromium.org/chromium/src/content/child/runtime_features.cc?type=cs&q=f:runtime_features.cc+WebRuntimeFeatures::EnableAutomationControlled&sq=package:chromium&l=147

**Pull request merged**
